[package]
name = "fsio"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
bitflags = "2.9.1"
libc = "1.0.0-alpha.1"
enum_flags = { path = "./enum_flags" }

[build-dependencies]
cfg_aliases = "0.2.1"
