[package]
name = "fsio"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
nix = { version = "0.30.1", features = ["fs", "dir"] }
thiserror = "2.0.12"
regex = "1.11.1"

serde = "1.0.219"
serde_json = "1.0.142"
serde_yaml = "0.9.34-deprecated"
toml = "0.9.5"