[package]
name = "fsio"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
libc = "1.0.0-alpha.1"
thiserror = "2.0.14"
bitflags = "2.9.1"

[build-dependencies]
cfg_aliases = "0.2.1"
