use crate::error::Error;

pub trait FromRaw<T>: Sized
where
    T: AsRef<usize>,
{
    fn from_raw(err: T) -> Self;
}

impl<T> FromRaw<T> for Error
where
    T: AsRef<usize>,
{
    fn from_raw(err: T) -> Self {
        match err.as_ref() {
            1 => Self::PermissionDenied,
            2 => Self::NotFound,
            3 => Self::NoSuchProcess,
            4 => Self::Interrupted,
            5 => Self::IoError,
            6 => Self::NoSuchDeviceOrAddress,
            7 => Self::ArgumentListTooLong,
            8 => Self::ExecFormatError,
            9 => Self::BadFileDescriptor,
            10 => Self::NoChildProcesses,
            11 => Self::ResourceDeadlockWouldOccur,
            12 => Self::OutOfMemory,
            13 => Self::AccessDenied,
            14 => Self::BadAddress,
            15 => Self::BlockDeviceRequired,
            16 => Self::DeviceBusy,
            17 => Self::AlreadyExists,
            18 => Self::CrossDeviceLink,
            19 => Self::NoSuchDevice,
            20 => Self::NotDirectory,
            21 => Self::IsDirectory,
            22 => Self::InvalidArgument,
            23 => Self::FileTableOverflow,
            24 => Self::TooManyOpenFiles,
            25 => Self::NotTTY,
            26 => Self::TextFileBusy,
            27 => Self::FileTooLarge,
            28 => Self::NoSpaceLeftOnDevice,
            29 => Self::IllegalSeek,
            30 => Self::ReadOnlyFilesystem,
            31 => Self::TooManyLinks,
            32 => Self::BrokenPipe,
            33 => Self::MathArgumentOutOfDomain,
            34 => Self::ResultTooLarge,
            35 => Self::ResourceUnavailableTryAgain,
            36 => Self::OperationInProgress,
            37 => Self::OperationAlreadyInProgress,
            38 => Self::SocketNotSupported,
            39 => Self::DestinationAddressRequired,
            40 => Self::MessageTooLong,
            41 => Self::ProtocolWrongTypeForSocket,
            42 => Self::ProtocolNotAvailable,
            43 => Self::ProtocolNotSupported,
            44 => Self::SocketTypeNotSupported,
            45 => Self::OperationNotSupported,
            46 => Self::ProtocolFamilyNotSupported,
            47 => Self::AddressFamilyNotSupported,
            48 => Self::AddressInUse,
            49 => Self::AddressNotAvailable,
            50 => Self::NetworkDown,
            51 => Self::NetworkUnreachable,
            52 => Self::NetworkReset,
            53 => Self::ConnectionAborted,
            54 => Self::ConnectionReset,
            55 => Self::NoBufferSpaceAvailable,
            56 => Self::SocketIsConnected,
            57 => Self::SocketNotConnected,
            58 => Self::Shutdown,
            59 => Self::TooManyReferences,
            60 => Self::TimedOut,
            61 => Self::ConnectionRefused,
            62 => Self::TooManySymbolicLinks,
            63 => Self::FileNameTooLong,
            64 => Self::HostDown,
            65 => Self::HostUnreachable,
            66 => Self::DirectoryNotEmpty,
            67 => Self::ProcessLimitReached,
            68 => Self::TooManyUsers,
            69 => Self::DiskQuotaExceeded,
            70 => Self::StaleFileHandle,
            71 => Self::RemoteResourceNotAvailable,
            72 => Self::BadRPC,
            73 => Self::RPCMismatch,
            74 => Self::ProgramUnavailable,
            75 => Self::ProgramMismatch,
            76 => Self::ProcedureUnavailable,
            77 => Self::NoLocksAvailable,
            78 => Self::FunctionNotImplemented,
            79 => Self::InappropriateFileType,
            80 => Self::AuthenticationError,
            81 => Self::NeedAuthentication,
            82 => Self::PowerOff,
            83 => Self::DeviceError,
            84 => Self::ValueOverflow,
            85 => Self::BadExecutable,
            86 => Self::BadArchitecture,
            87 => Self::SharedLibraryVersionMismatch,
            88 => Self::BadMachO,
            89 => Self::OperationCanceled,
            90 => Self::IdentifierRemoved,
            91 => Self::NoMessageAvailable,
            92 => Self::IllegalByteSequence,
            93 => Self::AttributeNotFound,
            94 => Self::BadMessage,
            95 => Self::MultihopAttempted,
            96 => Self::NoDataAvailable,
            97 => Self::LinkHasBeenSevered,
            98 => Self::NoStreamResources,
            99 => Self::NotStructuredStream,
            100 => Self::ProtocolError,
            101 => Self::TimerExpired,
            102 => Self::OperationNotSupportedOnSocket,
            103 => Self::NoPolicy,
            104 => Self::NotRecoverable,
            105 => Self::OwnerDead,
            106 => Self::QueueFull,
            _ => Self::Unknown,
        }
    }
}